let cachedHtml;

export function renderAdminHtml() {
  if (cachedHtml) return cachedHtml;
  cachedHtml = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>B站直播监控</title>
  <style>
    :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:#172033;background:#f6f8fb;line-height:1.45}
    *{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#eef4ff 0,#f6f8fb 250px);min-height:100vh}
    .shell{max-width:1180px;margin:0 auto;padding:30px 20px 56px}.topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:22px}
    .eyebrow{margin:0 0 5px;color:#4169c8;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.brand h1{margin:0;font-size:30px;letter-spacing:-.02em}.brand p{margin:7px 0 0;color:#667085;font-size:14px}
    .auth{display:flex;gap:8px;align-items:center;min-width:min(420px,100%)}.auth input{flex:1}.hint{color:#667085;font-size:12px}
    .button{border:0;border-radius:7px;padding:10px 14px;background:#245dcc;color:#fff;font-weight:700;cursor:pointer;white-space:nowrap}.button:hover{background:#174aa9}.button.secondary{background:#e8eefb;color:#245dcc}.button.secondary:hover{background:#dce6fa}.button.danger{background:#fff0f0;color:#bd2d38}.button.small{padding:6px 9px;font-size:12px}
    input,select{width:100%;border:1px solid #d5dce7;border-radius:7px;background:#fff;color:#172033;padding:10px 11px;font:inherit;outline:none}input:focus,select:focus{border-color:#7294e4;box-shadow:0 0 0 3px #dce7ff}
    .overview{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.metric,.panel{background:#fff;border:1px solid #e1e7f0;border-radius:10px;box-shadow:0 8px 24px rgba(27,53,94,.05)}.metric{padding:15px 16px}.metric-label{color:#667085;font-size:12px}.metric-value{display:block;margin-top:5px;font-size:23px;font-weight:800}.metric-value.good{color:#13845b}.metric-value.warn{color:#b86b00}
    .panel{padding:18px;margin-top:14px}.panel-header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:15px}.panel h2{margin:0;font-size:18px}.panel-subtitle{margin:4px 0 0;color:#667085;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.form{display:grid;grid-template-columns:140px 1fr 1fr auto;gap:8px;margin-bottom:12px}.form.target{grid-template-columns:140px 1fr 1fr auto}.settings-form{display:grid;grid-template-columns:150px 1fr 1fr 160px auto;gap:10px;align-items:center}.check{display:flex;align-items:center;gap:7px;color:#475467;font-size:13px}.check input{width:auto}
    .list{border-top:1px solid #edf0f5}.empty{padding:17px 0;color:#98a2b3;font-size:13px}.row{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 0;border-bottom:1px solid #edf0f5}.row:last-child{border-bottom:0}.row-main{min-width:0}.row-title{font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row-meta{margin-top:3px;color:#667085;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row-actions{display:flex;align-items:center;gap:7px;flex:none}.pill{border-radius:99px;padding:3px 8px;background:#eef2f7;color:#667085;font-size:11px;font-weight:700}.pill.live{background:#e8f8ef;color:#087443}.pill.off{background:#f1f3f5;color:#667085}.pill.error{background:#fff0f0;color:#bd2d38}.status{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.status-item{padding:10px 12px;background:#f8fafc;border-radius:7px}.status-label{display:block;color:#667085;font-size:11px}.status-value{display:block;margin-top:3px;font-size:13px;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.alert{margin-top:12px;padding:10px 12px;border-radius:7px;background:#fff7e6;color:#9a5a00;font-size:13px;display:none}.alert.show{display:block}
    @media(max-width:900px){.overview{grid-template-columns:repeat(2,1fr)}.form,.form.target,.settings-form{grid-template-columns:1fr 1fr}.form button,.form.target button,.settings-form button{grid-column:1/-1}.topbar{flex-direction:column}.auth{width:100%;min-width:0}}
    @media(max-width:640px){.shell{padding:22px 13px 42px}.brand h1{font-size:25px}.grid{grid-template-columns:1fr}.overview{gap:8px}.metric{padding:12px}.metric-value{font-size:20px}.status{grid-template-columns:1fr}.row{align-items:flex-start}.row-actions{flex-direction:column;align-items:flex-end}}
  </style>
</head>
<body>
  <main class="shell">
    <header class="topbar">
      <div class="brand"><p class="eyebrow">Bilibili Live Monitor</p><h1>直播监控</h1><p>每分钟检查状态，只在开播和下播时通知 QQ。</p></div>
      <div class="auth"><input id="password" type="password" placeholder="首次设置或登录管理员密码"><button class="button" onclick="loginOrSetup()">设置 / 登录</button><button class="button secondary" onclick="logout()">退出</button></div>
    </header>
    <div id="alert" class="alert"></div>
    <section class="overview"><div class="metric"><span class="metric-label">监控对象</span><strong id="metric-monitors" class="metric-value">-</strong></div><div class="metric"><span class="metric-label">通知目标</span><strong id="metric-targets" class="metric-value">-</strong></div><div class="metric"><span class="metric-label">最近检查</span><strong id="metric-checked" class="metric-value">-</strong></div><div class="metric"><span class="metric-label">待发送</span><strong id="metric-pending" class="metric-value">-</strong></div></section>
    <section class="panel"><div class="panel-header"><div><h2>运行状态</h2><p class="panel-subtitle">检查器和通知队列的实时状态</p></div><button class="button secondary small" onclick="loadAll()">刷新</button></div><div id="status" class="status"><div class="status-item"><span class="status-label">状态</span><span class="status-value">尚未加载</span></div></div></section>
    <div class="grid">
      <section class="panel"><div class="panel-header"><div><h2>监控对象</h2><p class="panel-subtitle">支持 B站 UID 或直播间号</p></div></div><form class="form" onsubmit="addMonitor(event)"><select id="mtype"><option value="room">直播间号</option><option value="uid">B站 UID</option></select><input id="mid" required placeholder="例如 21686237"><input id="mlabel" placeholder="备注（可选）"><button class="button">添加</button></form><div id="monitors" class="list"></div></section>
      <section class="panel"><div class="panel-header"><div><h2>通知目标</h2><p class="panel-subtitle">支持 QQ 私聊和群聊 OpenID</p></div></div><form class="form target" onsubmit="addTarget(event)"><select id="ttype"><option value="private">QQ 私聊</option><option value="group">QQ群聊</option></select><input id="tid" required placeholder="OpenID"><input id="tlabel" placeholder="备注（可选）"><button class="button">添加</button></form><div id="targets" class="list"></div></section>
    </div>
    <section class="panel"><div class="panel-header"><div><h2>监控设置</h2><p class="panel-subtitle">Cron 每分钟唤醒，实际检查按此间隔执行</p></div></div><form class="settings-form" onsubmit="saveSettings(event)"><label>检查间隔（分钟）<input id="interval" type="number" min="1" max="60" value="1"></label><label class="check"><input id="start" type="checkbox" checked> 开播通知</label><label class="check"><input id="end" type="checkbox" checked> 下播通知</label><label>消息格式<select id="format"><option value="text">普通文本</option><option value="markdown">Markdown</option></select></label><button class="button">保存设置</button></form></section>
    <section class="panel"><div class="panel-header"><div><h2>QQ机器人</h2><p class="panel-subtitle">凭证保存在 D1，ClientSecret 不会回显</p></div><span id="qq-state" class="pill">未配置</span></div><form class="form" onsubmit="saveQQ(event)"><input id="appid" required placeholder="QQ AppID"><input id="secret" type="password" placeholder="ClientSecret（留空保留）"><span></span><button class="button">保存凭证</button></form></section>
    <section class="panel"><div class="panel-header"><div><h2>B站数据源</h2><p class="panel-subtitle">出现 HTTP 412 时，可填写非 Cloudflare 出口的 HTTPS 代理；留空使用官方接口</p></div><span id="bili-state" class="pill">官方接口</span></div><form class="form" onsubmit="saveBilibili(event)"><input id="bili-url" placeholder="代理地址，例如 https://example.com/bilibili"><input id="bili-token" type="password" placeholder="代理令牌（留空保留）"><span></span><button class="button">保存数据源</button></form></section>
  </main>
  <script>
    const $=id=>document.getElementById(id);const sessionName='bili-live-admin-session';
    function token(){return sessionStorage.getItem(sessionName)||''}function headers(){return {'Authorization':token()?'Bearer '+token():'','Content-Type':'application/json'}}
    function showError(message){const a=$('alert');a.textContent=message;a.classList.add('show');setTimeout(()=>a.classList.remove('show'),5000)}
    async function authInfo(){const r=await fetch('/api/auth/status');return r.json()}
    async function loginOrSetup(){const password=$('password').value;if(password.length<12){showError('密码至少需要 12 个字符');return}try{const info=await authInfo();const path=info.configured?'/api/auth/login':'/api/auth/setup';const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw Error(d.error||'认证失败');sessionStorage.setItem(sessionName,d.token);$('password').value='';loadAll()}catch(e){showError(e.message)}}
    async function logout(){sessionStorage.removeItem(sessionName);try{await fetch('/api/auth/logout',{method:'POST',headers:headers()})}catch{}loadAll()}
    async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{...headers(),...(opt.headers||{})}});const d=await r.json().catch(()=>({error:r.statusText}));if(!r.ok)throw Error(d.error||'请求失败');return d}
    function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    function statusText(value){return value===1?'直播中':value===0?'未开播':'未检查'}
    async function loadAll(){try{const info=await authInfo();if(!token()){$('status').innerHTML='<div class="status-item"><span class="status-label">认证</span><span class="status-value">'+(info.configured?'请输入密码登录':'首次设置管理员密码')+'</span></div>';return}const [s,m,t,set,q,b]=await Promise.all([api('/api/status'),api('/api/monitors'),api('/api/targets'),api('/api/settings'),api('/api/qq-config'),api('/api/bilibili-config')]);$('metric-monitors').textContent=(s.monitors.enabled||0)+' / '+(s.monitors.total||0);$('metric-targets').textContent=(s.targets.enabled||0)+' / '+(s.targets.total||0);$('metric-checked').textContent=s.job?.last_checked_count??0;$('metric-pending').textContent=s.pending_outbox??0;$('status').innerHTML='<div class="status-item"><span class="status-label">最近完成</span><span class="status-value">'+esc(s.job?.last_finished_at||'尚未执行')+'</span></div><div class="status-item"><span class="status-label">下次检查</span><span class="status-value">'+esc(s.job?.next_check_at||'等待调度')+'</span></div><div class="status-item"><span class="status-label">最近错误</span><span class="status-value">'+esc(s.job?.last_error||'无')+'</span></div>';$('monitors').innerHTML=m.monitors.map(x=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(x.label||x.source_id)+'</div><div class="row-meta">'+esc(x.type)+' · UID '+esc(x.uid)+' · 房间 '+esc(x.room_id||'未解析')+'</div></div><div class="row-actions"><span class="pill '+(x.live_status===1?'live':x.live_status===0?'off':'')+'">'+statusText(x.live_status)+'</span><button class="button danger small" onclick="delItem(\"/api/monitors/'+x.id+'\")">删除</button></div></div>').join('')||'<div class="empty">暂无监控对象</div>';$('targets').innerHTML=t.targets.map(x=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(x.label||x.target_id)+'</div><div class="row-meta">'+esc(x.type)+' · '+esc(x.target_id)+'</div></div><div class="row-actions"><span class="pill live">启用</span><button class="button danger small" onclick="delItem(\"/api/targets/'+x.id+'\")">删除</button></div></div>').join('')||'<div class="empty">暂无通知目标</div>';$('interval').value=set.interval_minutes;$('start').checked=set.notify_start;$('end').checked=set.notify_end;$('format').value=set.format;$('appid').value=q.app_id||'';$('qq-state').textContent=q.client_secret_configured?'已配置':'未配置';$('qq-state').className='pill '+(q.client_secret_configured?'live':'');$('bili-url').value=b.base_url||'';$('bili-state').textContent=b.base_url?'代理已启用':'官方接口';$('bili-state').className='pill '+(b.base_url?'live':'')}catch(e){if(token())showError(e.message)}}
    async function addMonitor(e){e.preventDefault();try{await api('/api/monitors',{method:'POST',body:JSON.stringify({type:$('mtype').value,id:$('mid').value,label:$('mlabel').value})});$('mid').value='';$('mlabel').value='';loadAll()}catch(e){showError(e.message)}}
    async function addTarget(e){e.preventDefault();try{await api('/api/targets',{method:'POST',body:JSON.stringify({type:$('ttype').value,id:$('tid').value,label:$('tlabel').value})});$('tid').value='';$('tlabel').value='';loadAll()}catch(e){showError(e.message)}}
    async function saveSettings(e){e.preventDefault();try{await api('/api/settings',{method:'PUT',body:JSON.stringify({interval_minutes:Number($('interval').value),notify_start:$('start').checked,notify_end:$('end').checked,format:$('format').value})});loadAll()}catch(e){showError(e.message)}}
    async function saveQQ(e){e.preventDefault();try{await api('/api/qq-config',{method:'PUT',body:JSON.stringify({app_id:$('appid').value.trim(),client_secret:$('secret').value})});$('secret').value='';loadAll()}catch(e){showError(e.message)}}
    async function saveBilibili(e){e.preventDefault();try{await api('/api/bilibili-config',{method:'PUT',body:JSON.stringify({base_url:$('bili-url').value.trim(),access_token:$('bili-token').value})});$('bili-token').value='';loadAll()}catch(e){showError(e.message)}}
    async function delItem(path){if(!confirm('确认删除？'))return;try{await api(path,{method:'DELETE'});loadAll()}catch(e){showError(e.message)}}
    async function manualCheck(){try{await api('/api/check',{method:'POST'});loadAll()}catch(e){showError(e.message)}}
    loadAll();setInterval(loadAll,30000);
  </script>
</body></html>`;
  return cachedHtml;
}
